### ISSUE TITLE
Encountered an error while trying to build the Gulp

### ISSUE THREAD

**Issue by leonism** [themesberg/pixel-bootstrap-ui-kit#22]
**Describe the bug**
While trying to run the Gulp command, encountered the following error:

dyld: lazy symbol binding failed: Symbol not found: _FSEventStreamCreate
  Referenced from: /Volumes/DATA/Gulp/pixel-lite/node_modules/fsevents/build/Release/fse.node
  Expected in: flat namespace

dyld: Symbol not found: _FSEventStreamCreate
  Referenced from: /Volumes/DATA/Gulp/pixel-lite/node_modules/fsevents/build/Release/fse.node
  Expected in: flat namespace

**To Reproduce**
1. Go to project folder, the pixel-lite'
2. Click on 'run the Gulp command.'
3. See error

dyld: lazy symbol binding failed: Symbol not found: _FSEventStreamCreate
  Referenced from: /Volumes/DATA/Gulp/pixel-lite/node_modules/fsevents/build/Release/fse.node
  Expected in: flat namespace

dyld: Symbol not found: _FSEventStreamCreate
  Referenced from: /Volumes/DATA/Gulp/pixel-lite/node_modules/fsevents/build/Release/fse.node
  Expected in: flat namespace

**Expected behavior**

**Screenshots**
See screenshot 
https://drive.google.com/file/d/1IawULbnlMS1pcA3dCjkwExnPpSaNDDQz/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome

**Comment by zoltanszogyenyi** [comment]
Hey @leonism, I have just cloned the repository into a new folder and ran npm install having also Gulp installed globally. I think your problem is a local Node problem. Which version are you running on? Also I can't seem to access the drive file unfortunately, I asked for the access.

**Comment by leonism** [comment]
Could you access them now? https://drive.google.com/file/d/1IawULbnlMS1pcA3dCjkwExnPpSaNDDQz/view?usp=sharing

**Comment by zoltanszogyenyi** [comment]
@leonism please check this out and install the latest version of Xcode and Node using brew https://github.com/fsevents/fsevents/issues/313

**Comment by leonism** [comment]
This is rather a simple solution, I simply deleted the `/fsevents/`from the `node_modules` and it worked. Don't know if they had any effect on the exported folder, that created the uncollapsible accordion component in any way?

**Comment by zoltanszogyenyi** [comment]
Ah no, the accordion collapse didn't work because the jQuery and Bootstrap version was not compatible. It happened the same thing on my environment as well, but that has been fixed!

**Comment by leonism** [comment]
> @leonism please check this out and install the latest version of Xcode and Node using brew [fsevents/fsevents#313](https://github.com/fsevents/fsevents/issues/313)

I came across that thread already, and ran the same issues, I'm already on the latest version of Xcode (well at least for Mojave, not yet on the latest OS though).
