### ISSUE TITLE
Accordion Won't Collapse

### ISSUE THREAD

**Issue by leonism** [themesberg/pixel-bootstrap-ui-kit#23]
**Describe the bug**
This is rather an unusual post perhaps, I know from the online documentation the accordion working out just fine. But in my local instance, once I've downloaded the Zip file and managed to run the `gulp build:dev`, the output files in the html&css folder (the unminified version), and browse to the Accordion section, the Accordion don't work, they don't collapse basically. Similarly, if I ran the `gulp build:dist`, and check the dist folder, the similar occurrence is happening. 

**To Reproduce**
1. Go to the pixel folder.
2. Run the `gulp build:dev` or the `gulp build:dist`
3. Check the output in the appropriate folders.
4. The accordion effect don't work.

**Expected behavior**
It should work similar to the online version, the accordion should be collapsible much like the online version.

**Screenshots**
- here's the exported folder link: https://drive.google.com/drive/folders/1gMBsS8tJfahr0gxZmQl6WZo7SZiFSwKI?usp=sharing
- here's the screencap https://drive.google.com/file/d/1gtdvz6yn8vrVXy5ydibCib19jM-L3DbC/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by zoltanszogyenyi** [comment]
Hey @leonism, thanks for the notice. I'll check this out ASAP. Please be aware that I can't access the drive files.

**Comment by zoltanszogyenyi** [comment]
@leonism fixed this. Problem was that the newest jQuery v3.5 was not compatible with this version of Bootstrap. You can take the latest master branch to get the changes before we make a release. Cheers!

**Comment by leonism** [comment]
Could you access them now? https://drive.google.com/file/d/1gtdvz6yn8vrVXy5ydibCib19jM-L3DbC/view?usp=sharing

**Comment by zoltanszogyenyi** [comment]
@leonism yep, however the problem was with the jQuery version as it was not compatible with the Bootstrap version. So it's fixed now if you pull the latest commit from the master branch. Thanks for letting us know!
