### ISSUE TITLE
Invisible navbar on contact page

### ISSUE THREAD

**Issue by RinatValiullov** [themesberg/pixel-bootstrap-ui-kit#3]
I noticed strange behaviour of UI on a [contact page](https://demo.themesberg.com/pixel-lite/html/pages/contact.html). Attach screen recording below :point_down: 

![sa](https://user-images.githubusercontent.com/9755333/76936366-aa8f4580-6914-11ea-84f5-b881a2229a9f.gif)

**Comment by zoltanszogyenyi** [comment]
Thanks @RinatValiullov. We're launching v3 this week, I'll make sure this no longer happens.

**Comment by zoltanszogyenyi** [comment]
@RinatValiullov version 3 is released. Issue closed :)
