### ISSUE TITLE
Navbar menu items disappear on light theme

### ISSUE THREAD

**Issue by jesusloplar** [themesberg/pixel-bootstrap-ui-kit#30]
Hi, I am making an html file out of the `app-landing.html` file. While browsing within the web with this html, the menu bar disappears in scrolled down positions.

I leave here a video... https://www.dropbox.com/s/otz0omkx3vv8nzj/Scroll%20down%20pixel.MP4?dl=0

Someone knows a workaround?

Many thanks in advance!!

**Comment by zoltanszogyenyi** [comment]
Hey @jesusloplar,

Looks like a CSS problem when the background is transparent behind the navigation bar. We'll address this in the next update. Thank you.

**Comment by zoltanszogyenyi** [comment]
@jesusloplar this issue has been addressed in the [v5.4.0 update](https://themesberg.com/product/ui-kit/pixel-pro-premium-bootstrap-5-ui-kit).
