### ISSUE TITLE
Navbar dropdown menu resize bug

### ISSUE THREAD

**Issue by vidasci** [themesberg/pixel-bootstrap-ui-kit#33]
**Describe the bug**
When resizing to smaller browser width and going back to full width, navbar dropdown menu is broken

**To Reproduce**
1. Open home page
2. Resize browser to a size where nav-menu items collapse
3. Click on hamburger-menu item to open dropdown menu
4. With dropdown-menu open, resize browser back to full width
5. All menu items are now expanded and there is no way (apart from refreshing the page) to get rid of the dropped down menus

**Expected behavior**
Same dropdown functionality as before resizing browser.

**Screenshots**
![resize_bug](https://user-images.githubusercontent.com/49881761/119964395-75b35f80-bfa9-11eb-869f-4f8c279632f6.gif)

**Comment by vidasci** [comment]
If anyone experiences the same problem, here is a temporary (hacky) fix: 

``` javascript
window.addEventListener("resize", function(){
    if (document.body.clientWidth > breakpoints.lg){
        document.getElementsByClassName('navbar-collapse')[0].classList.remove('show')
    }
})
```

**Comment by vidasci** [comment]
Accidentally closed issue

**Comment by zoltanszogyenyi** [comment]
Hey @vidasci,

Thanks for opening the issue and for the temporary fix. We'll address this in the next update where we will also bump the Bootstrap version to a stable one.

**Comment by zoltanszogyenyi** [comment]
@vidasci there is a script in pixel.js where the hover and click actions are being added. For example, when on mobile, there is no hover action, and on the desktop there is. It is true that this can happen if you resize the browser window, but if you access the web page from a mobile/tablet device, or if you refresh the browser in a new viewport setting, this error does not happen.

**Comment by vidasci** [comment]
I agree it is not very likely to happen as it will only occur when resizing the browser window to small and than back to large, thanks for looking into it!
