### ISSUE TITLE
Submenu for dashboard

### ISSUE THREAD

**Issue by bioworkflows** [themesberg/pixel-bootstrap-ui-kit#38]
We love the layout of the dashboard (e.g. [this demo](https://demo.themesberg.com/pixel-pro/v5/html/dashboard/account.html)) but we are having trouble adding submenus to the left panel. More specifically, we have many settings and would like to divide them into multiple pages. Ideally,

1. The '>' symbol after "settings" should be "+" (or something else that is indicative of submenu)
2. Clicking the menu would expand the submenu and "+" should rotate similar to what accordion does.

It would be really helpful if you could give me a short piece of code to demonstrate the addition and expansion of submenus.

Thanks,

**Comment by BoPeng** [comment]
I had a further look into the code and found that the menu is rendered as buttons and dropdown in mobile mode. Whereas it is relatively easy to keep the tree structure in modile, adding submenus side by side with the dropdown can be challenging.
